# Generated by Django 4.2.3 on 2023-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('course', models.IntegerField()),
                ('instrument', models.CharField(choices=[('guitar', 'Гитара'), ('piano', 'Пианино'), ('violin', 'Скрипка'), ('drums', 'Барабаны'), ('flute', 'Флейта')], max_length=10)),
                ('performance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('has_paid', models.BooleanField()),
            ],
        ),
    ]
